version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/reedchan7/aliyungo
    steps:
    - checkout
    - run: go get -t -d -v ./...
    - run: go test -run=nope ./...
    - run: go vet ./...

